server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dbmaster?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        username: root
        password: 136436
      slave:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dbslave?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        username: root
        password: 136436
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dbmaster?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: 136436
mybatis:
  type-aliases-package: com.tabwu.entity

logging:
  level:
    com.tabwu: debug
